# Generated by Django 3.1 on 2020-08-18 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('health', 'Health'), ('culture', 'Culture'), ('business', 'Business'), ('oil', 'Oil'), ('sports', 'Sports'), ('agriculture', 'Agriculture'), ('travel', 'Travel')], default='health', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
