# Generated by Django 3.1 on 2020-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('culture', 'Culture'), ('business', 'Business'), ('oil', 'Oil'), ('sports', 'Sports'), ('agriculture', 'Agriculture'), ('travel', 'Travel'), ('Blog', 'Blog')], default='health', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
