# Generated by Django 3.1 on 2020-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200905_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
