# Generated by Django 3.1 on 2020-09-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200905_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=40),
        ),
    ]
